#!/usr/bin/env bash
#
# sync-simn.sh — vendor the SIMN engine into your Godot project.
#
# Reference copy shipped with SIMN. Drop this into your project's scripts/
# folder. It consumes SIMN as a drop-in Godot addon rather than building it
# in-tree: it clones the public SIMN repo at a pinned commit and copies its
# `crates/` + `content/` into `godot/addons/simn/` (which you gitignore). Your
# project's root Cargo.toml lists those crates as workspace members, so a normal
# `cargo build` from the repo root builds the bridge as usual. See this folder's
# README.md for the one-time setup (workspace members, .gdextension).
#
# Two modes:
#
#   COPY (default) - clone SIMN at the pin and drop a frozen snapshot into
#   godot/addons/simn/. Reproducible; what contributors and CI use. Engine
#   source is read-only: make changes upstream in SIMN, push, bump
#   scripts/SIMN_VERSION, and re-run.
#
#   LINK (--link <path>) - symlink godot/addons/simn/{crates,content} at a
#   local SIMN working clone instead of copying. For active engine dev: edit
#   the clone and the build picks it up live, no copy/pin-bump to test.
#   Commit/push from the clone; bump scripts/SIMN_VERSION when your project
#   formally adopts a version. Re-run plain `sync-simn.sh` to drop back to the
#   pinned snapshot (removing the symlinks does not touch the clone).
#   (Symlinks: Linux/macOS/WSL. Native Windows needs a junction or Dev Mode.)
#
# Usage:
#   scripts/sync-simn.sh                 # COPY: sync the pin in scripts/SIMN_VERSION
#   scripts/sync-simn.sh --ref <sha|tag> # COPY: sync a specific ref (does not edit the pin)
#   scripts/sync-simn.sh --link <path>   # LINK: symlink to a local SIMN clone
#   scripts/sync-simn.sh --no-build      # skip the cargo build at the end
#
set -euo pipefail

REPO_URL="https://github.com/trapframestudio/simn.git"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
ADDON_DIR="$REPO_ROOT/godot/addons/simn"
PIN_FILE="$SCRIPT_DIR/SIMN_VERSION"

REF=""
DO_BUILD=1
LINK_PATH=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --ref) REF="${2:?--ref needs a value}"; shift 2 ;;
    --link) LINK_PATH="${2:?--link needs a path to a SIMN clone}"; shift 2 ;;
    --no-build) DO_BUILD=0; shift ;;
    -h|--help) sed -n '2,34p' "$0"; exit 0 ;;
    *) echo "sync-simn: unknown arg '$1'" >&2; exit 2 ;;
  esac
done

build_bridge() {
  [[ "$DO_BUILD" -eq 1 ]] || return 0
  echo "sync-simn: building bridge (cargo build -p simn-godot) ..."
  ( cd "$REPO_ROOT" && cargo build -p simn-godot )
  echo "sync-simn: built libsimn_godot into $REPO_ROOT/target/debug/"
}

# ---- LINK mode: symlink the addon at a local SIMN working clone ----
if [[ -n "$LINK_PATH" ]]; then
  clone="$(cd "$LINK_PATH" 2>/dev/null && pwd)" \
    || { echo "sync-simn: --link path not found: $LINK_PATH" >&2; exit 1; }
  for d in crates content; do
    [[ -d "$clone/$d" ]] || { echo "sync-simn: $clone is not a SIMN clone (missing $d/)" >&2; exit 1; }
  done
  echo "sync-simn: LINK mode -> $clone"
  mkdir -p "$ADDON_DIR"
  rm -rf "$ADDON_DIR/crates" "$ADDON_DIR/content" \
         "$ADDON_DIR/LICENSE-MIT" "$ADDON_DIR/LICENSE-APACHE"
  ln -s "$clone/crates" "$ADDON_DIR/crates"
  ln -s "$clone/content" "$ADDON_DIR/content"
  linked_sha="$(git -C "$clone" rev-parse HEAD 2>/dev/null || echo 'not-a-git-checkout')"
  cat > "$ADDON_DIR/.simn-synced" <<EOF
# Generated by scripts/sync-simn.sh --link -- do not edit.
mode     = link
clone    = $clone
head     = $linked_sha
note     = LIVE symlink; edits in the clone build directly. Not the pinned snapshot.
EOF
  echo "sync-simn: linked (clone HEAD $linked_sha). Edits in the clone are now live."
  echo "sync-simn: NOTE this is dev-only; CI/contributors use copy mode + scripts/SIMN_VERSION."
  build_bridge
  echo "sync-simn: done."
  exit 0
fi

if [[ -z "$REF" ]]; then
  [[ -f "$PIN_FILE" ]] || { echo "sync-simn: no $PIN_FILE and no --ref given" >&2; exit 1; }
  REF="$(tr -d '[:space:]' < "$PIN_FILE")"
fi
[[ -n "$REF" ]] || { echo "sync-simn: empty ref" >&2; exit 1; }

echo "sync-simn: pinning SIMN @ $REF"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "sync-simn: cloning $REPO_URL ..."
git clone --quiet "$REPO_URL" "$TMP/simn"
git -C "$TMP/simn" checkout --quiet "$REF"
SYNCED_SHA="$(git -C "$TMP/simn" rev-parse HEAD)"

for d in crates content; do
  [[ -d "$TMP/simn/$d" ]] || { echo "sync-simn: SIMN checkout missing $d/" >&2; exit 1; }
done

echo "sync-simn: vendoring into $ADDON_DIR ..."
mkdir -p "$ADDON_DIR"
# Replace the vendored trees wholesale. We deliberately do NOT copy SIMN's
# root Cargo.toml/Cargo.lock: your project root is the one and only Cargo
# workspace, and a nested [workspace] underneath it is an error.
rm -rf "$ADDON_DIR/crates" "$ADDON_DIR/content" \
       "$ADDON_DIR/LICENSE-MIT" "$ADDON_DIR/LICENSE-APACHE"
cp -R "$TMP/simn/crates" "$ADDON_DIR/crates"
cp -R "$TMP/simn/content" "$ADDON_DIR/content"
for f in LICENSE-MIT LICENSE-APACHE; do
  [[ -f "$TMP/simn/$f" ]] && cp "$TMP/simn/$f" "$ADDON_DIR/$f"
done

cat > "$ADDON_DIR/.simn-synced" <<EOF
# Generated by scripts/sync-simn.sh — do not edit.
ref      = $REF
commit   = $SYNCED_SHA
synced   = $(date -u +%Y-%m-%dT%H:%M:%SZ)
source   = $REPO_URL
EOF

echo "sync-simn: vendored SIMN $SYNCED_SHA"

build_bridge
echo "sync-simn: done."
